name: coreflame
description: A polished 2D game template built with Flutter and Flame.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flame: ^1.38.2
  flutter:
    sdk: flutter
  state_launcher_flutter:
    git:
      url: https://github.com/aleclarson/state_launcher_flutter.git
      ref: 77b9a41c4f4fc8f213c6d48e5fc6bee8187a4013

dev_dependencies:
  flame_test: ^2.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  vm_service: ^15.3.0

flutter:
  uses-material-design: true
